import { Deck, Prompt } from './types';

export const DECKS: Deck[] = [
  {
    id: 'reflection',
    name: 'Reflection',
    description: 'Practice speaking about personal experiences and opinions.',
    roomSubtitle: 'Develop confidence in articulating personal views and individual perspectives.',
    environmentMood: 'A quiet forest at dawn. Deep greens and focused atmosphere.',
    accentColor: '#1B2E1E',
    glowClass: 'from-emerald-950/80 via-emerald-900/30 to-transparent',
    cardBgClass: 'bg-[#121f15]',
    iconBgClass: 'bg-[#1B2E1E]',
    iconName: 'Trees',
  },
  {
    id: 'stories',
    name: 'Stories',
    description: 'Practice storytelling with clear structure and engaging delivery.',
    roomSubtitle: 'Structure engaging narratives with captivating pacing and vocal clarity.',
    environmentMood: 'An old library. Warm wood, aged paper, storytelling focus.',
    accentColor: '#3D2B1F',
    glowClass: 'from-amber-950/80 via-amber-900/30 to-transparent',
    cardBgClass: 'bg-[#261b14]',
    iconBgClass: 'bg-[#3D2B1F]',
    iconName: 'BookOpen',
  },
  {
    id: 'life',
    name: 'Life',
    description: 'Practice discussing everyday topics with confidence.',
    roomSubtitle: 'Build verbal fluency when discussing practical daily situations.',
    environmentMood: 'Slate blue horizons, gentle breeze, grounded focus.',
    accentColor: '#1E293B',
    glowClass: 'from-slate-900/80 via-slate-800/30 to-transparent',
    cardBgClass: 'bg-[#131b26]',
    iconBgClass: 'bg-[#1E293B]',
    iconName: 'Compass',
  },
  {
    id: 'philosophy',
    name: 'Philosophy',
    description: 'Practice organizing complex ideas into clear explanations and arguments.',
    roomSubtitle: 'Refine structured reasoning and express abstract concepts clearly.',
    environmentMood: 'Deep indigo accents, intellectual clarity, crisp acoustics.',
    accentColor: '#1E1B4B',
    glowClass: 'from-indigo-950/80 via-indigo-900/30 to-transparent',
    cardBgClass: 'bg-[#141233]',
    iconBgClass: 'bg-[#1E1B4B]',
    iconName: 'Sparkles',
  },
  {
    id: 'spirituality',
    name: 'Religion & Spirituality',
    description: 'Practice discussing beliefs and perspectives respectfully and thoughtfully.',
    roomSubtitle: 'Articulate deep values, core beliefs, and convictions with poise.',
    environmentMood: 'Respectful atmosphere, soft golden light, focused quiet.',
    accentColor: '#4A3E1B',
    glowClass: 'from-yellow-950/80 via-amber-900/30 to-transparent',
    cardBgClass: 'bg-[#29220e]',
    iconBgClass: 'bg-[#4A3E1B]',
    iconName: 'SunMedium',
  },
  {
    id: 'imagination',
    name: 'Imagination',
    description: 'Practice creative thinking and spontaneous speaking.',
    roomSubtitle: 'Unlock vocal agility and rapid creative improvisation.',
    environmentMood: 'Organic movement, vibrant purple-cyan aura, expansive creativity.',
    accentColor: '#2A1B4E',
    glowClass: 'from-purple-950/80 via-fuchsia-900/30 to-transparent',
    cardBgClass: 'bg-[#1a1131]',
    iconBgClass: 'bg-[#2A1B4E]',
    iconName: 'Palette',
  },
  {
    id: 'fun',
    name: 'Fun',
    description: 'Practice conversational fluency through lighthearted topics.',
    roomSubtitle: 'Build quick, engaging, and relaxed conversational flow.',
    environmentMood: 'Warm orange glow, spontaneous delight, dynamic energy.',
    accentColor: '#4A261B',
    glowClass: 'from-orange-950/80 via-orange-900/30 to-transparent',
    cardBgClass: 'bg-[#2b160f]',
    iconBgClass: 'bg-[#4A261B]',
    iconName: 'Smile',
  },
  {
    id: 'relationships',
    name: 'Relationships',
    description: 'Practice communicating about emotions and interpersonal situations.',
    roomSubtitle: 'Express interpersonal feelings and empathetic communication clearly.',
    environmentMood: 'Safe intimate space, natural soft lighting, empathetic clarity.',
    accentColor: '#451A22',
    glowClass: 'from-rose-950/80 via-rose-900/30 to-transparent',
    cardBgClass: 'bg-[#291014]',
    iconBgClass: 'bg-[#451A22]',
    iconName: 'Heart',
  },
  {
    id: 'career',
    name: 'Career',
    description: 'Practice professional communication, interviews, presentations, and leadership discussions.',
    roomSubtitle: 'Master executive presence, persuasive delivery, and professional interviews.',
    environmentMood: 'Emerald accents, elegant geometry, executive presence.',
    accentColor: '#064E3B',
    glowClass: 'from-emerald-950/80 via-teal-900/30 to-transparent',
    cardBgClass: 'bg-[#042e23]',
    iconBgClass: 'bg-[#064E3B]',
    iconName: 'Building2',
  },
  {
    id: 'medicine',
    name: 'Medicine & Dentistry',
    description: 'Practice explaining medical and dental concepts clearly to patients, students, and colleagues.',
    roomSubtitle: 'Explain complex health, clinical, and scientific topics with clarity and empathy.',
    environmentMood: 'Precision, trust, empathetic clarity, clinical focus.',
    accentColor: '#134E4A',
    glowClass: 'from-teal-950/80 via-cyan-900/30 to-transparent',
    cardBgClass: 'bg-[#0b2e2b]',
    iconBgClass: 'bg-[#134E4A]',
    iconName: 'Activity',
  },
  {
    id: 'surprise',
    name: 'Surprise',
    description: 'Practice speaking confidently on unexpected topics.',
    roomSubtitle: 'Test your spontaneous speaking skills on random topics.',
    environmentMood: 'Unpredictable challenges, instant verbal readiness.',
    accentColor: '#313030',
    glowClass: 'from-neutral-900/80 via-neutral-800/30 to-transparent',
    cardBgClass: 'bg-[#1f1f1f]',
    iconBgClass: 'bg-[#313030]',
    iconName: 'Shuffle',
  },
];

export const PROMPTS: Prompt[] = [
  // Reflection
  { id: 'ref-1', deckId: 'reflection', text: 'What belief have you changed your mind about?' },
  { id: 'ref-2', deckId: 'reflection', text: 'What hard truth are you currently choosing to avoid?' },
  { id: 'ref-3', deckId: 'reflection', text: 'When did you last feel completely present in your body?' },
  { id: 'ref-4', deckId: 'reflection', text: 'What is a decision you made that altered your trajectory?' },
  { id: 'ref-5', deckId: 'reflection', text: 'What does peace look like for you in your current season?' },
  { id: 'ref-6', deckId: 'reflection', text: 'What mistake taught you something you could not have learned otherwise?' },

  // Stories
  { id: 'sto-1', deckId: 'stories', text: 'Describe a stranger you met once but have never forgotten.' },
  { id: 'sto-2', deckId: 'stories', text: 'Tell the story of a place from your past that no longer exists.' },
  { id: 'sto-3', deckId: 'stories', text: 'What is the most unexpected act of quiet kindness you ever witnessed?' },
  { id: 'sto-4', deckId: 'stories', text: 'Describe a night where everything went off script, but turned out memorable.' },
  { id: 'sto-5', deckId: 'stories', text: 'Recount a moment when you felt entirely outside your comfort zone.' },

  // Life
  { id: 'lif-1', deckId: 'life', text: 'What simple daily ritual grounds you when life feels chaotic?' },
  { id: 'lif-2', deckId: 'life', text: 'How has your definition of personal success evolved over the past five years?' },
  { id: 'lif-3', deckId: 'life', text: 'What boundary lesson did you have to learn the hard way?' },
  { id: 'lif-4', deckId: 'life', text: 'If you could eliminate one friction point from your routine, what would it be?' },
  { id: 'lif-5', deckId: 'life', text: 'What advice would you offer to your younger self five years ago?' },

  // Philosophy
  { id: 'phi-1', deckId: 'philosophy', text: 'Is it better to seek intellectual certainty or embrace ongoing ambiguity?' },
  { id: 'phi-2', deckId: 'philosophy', text: 'Do we shape our tools, or do our tools inevitably shape us?' },
  { id: 'phi-3', deckId: 'philosophy', text: 'What transforms a conversation from transactional exchange into genuine dialogue?' },
  { id: 'phi-4', deckId: 'philosophy', text: 'Does suffering possess intrinsic meaning, or is meaning created in how we respond?' },
  { id: 'phi-5', deckId: 'philosophy', text: 'What is the relationship between freedom and responsibility?' },

  // Religion & Spirituality
  { id: 'spi-1', deckId: 'spirituality', text: 'Where do you turn for solace when logical explanation falls short?' },
  { id: 'spi-2', deckId: 'spirituality', text: 'What does grace look like when expressed in practical human terms?' },
  { id: 'spi-3', deckId: 'spirituality', text: 'How do you cultivate moments of inner silence in a hyper-connected world?' },
  { id: 'spi-4', deckId: 'spirituality', text: 'What sacred duty do we owe to future generations we will never meet?' },
  { id: 'spi-5', deckId: 'spirituality', text: 'How do you define faith when circumstances feel uncertain?' },

  // Imagination
  { id: 'ima-1', deckId: 'imagination', text: 'If humans possessed a sixth sense that detected emotion, how would architecture change?' },
  { id: 'ima-2', deckId: 'imagination', text: 'Describe a world where sleep is obsolete and society lives in continuous twilight.' },
  { id: 'ima-3', deckId: 'imagination', text: 'If you could preserve one piece of human creation for an alien civilization, what would it be?' },
  { id: 'ima-4', deckId: 'imagination', text: 'What would a city designed entirely around human tranquility look like?' },
  { id: 'ima-5', deckId: 'imagination', text: 'Describe an ideal day 50 years into the future.' },

  // Fun
  { id: 'fun-1', deckId: 'fun', text: 'What is a completely trivial hill you are secretly willing to die on?' },
  { id: 'fun-2', deckId: 'fun', text: 'If you could instantly acquire a useless world-class talent, what would it be?' },
  { id: 'fun-3', deckId: 'fun', text: 'What is the most bizarre food combination you genuinely enjoy?' },
  { id: 'fun-4', deckId: 'fun', text: 'If animals gained speech tomorrow, which species would be the most unbearable?' },
  { id: 'fun-5', deckId: 'fun', text: 'What movie plot would be solved in 5 minutes if characters just communicated?' },

  // Relationships
  { id: 'rel-1', deckId: 'relationships', text: 'What does unspoken trust feel like between two close friends?' },
  { id: 'rel-2', deckId: 'relationships', text: 'How do you express care when spoken words feel insufficient?' },
  { id: 'rel-3', deckId: 'relationships', text: 'What quality do you value most deeply in your inner circle?' },
  { id: 'rel-4', deckId: 'relationships', text: 'How do you navigate fundamental disagreement while maintaining respect?' },
  { id: 'rel-5', deckId: 'relationships', text: 'What is a lesson someone close to you taught you without realizing it?' },

  // Career
  { id: 'car-1', deckId: 'career', text: 'What work endeavor made you feel most effective and alive?' },
  { id: 'car-2', deckId: 'career', text: 'How do you balance high professional ambition with present contentment?' },
  { id: 'car-3', deckId: 'career', text: 'What leadership quality do you admire most in leaders you have known?' },
  { id: 'car-4', deckId: 'career', text: 'What is the best piece of career advice you intentionally ignored?' },
  { id: 'car-5', deckId: 'career', text: 'How do you know when it is time to pivot versus double down on a project?' },

  // Medicine & Dentistry
  { id: 'med-1', deckId: 'medicine', text: 'How do you articulate complex clinical risk to a frightened patient?' },
  { id: 'med-2', deckId: 'medicine', text: 'What role does empathy play when time and accuracy are both critical?' },
  { id: 'med-3', deckId: 'medicine', text: 'How do you preserve grace and composure in high-pressure clinical moments?' },
  { id: 'med-4', deckId: 'medicine', text: 'What clinical breakthrough in your lifetime inspires you most?' },
  { id: 'med-5', deckId: 'medicine', text: 'How can healthcare providers foster trust before opening a conversation?' },
];
