const fs = require('fs');
const crypto = require('crypto');

const deckId = 'dentistry';

const matrix = {
  frames: [
    "Explain the pathophysiology of [X] to a concerned patient with no medical background.",
    "Walk a dental student through the diagnostic workup and treatment planning for [X].",
    "How do you break bad news regarding a severe case of [X] to a patient?",
    "Describe the ethical considerations when a patient refuses standard care for [X].",
    "Explain the mechanism of action for the primary treatment or intervention for [X].",
    "Discuss the long-term prognosis and lifestyle modifications required after treating [X].",
    "How do you manage the expectations of a patient dealing with aesthetic concerns related to [X]?",
    "Describe a situation where [X] presents with highly atypical symptoms.",
    "How do you address a patient's misinformation regarding [X] found online?",
    "Explain the risks, benefits, and alternatives of surgical or invasive intervention for [X].",
    "How do you handle a scenario where [X] requires immediate emergency triage?",
    "Describe the role of preventative care and early intervention in reducing the incidence of [X].",
    "Explain how [X] might complicate other systemic health conditions.",
    "How do you collaborate with a multidisciplinary team (e.g., oral surgeons, orthodontists) to manage [X]?",
    "Discuss the psychological toll that chronic pain from [X] takes on a patient."
  ],
  subjects: [
    "Advanced Periodontitis",
    "Impacted Third Molars",
    "Temporomandibular Joint (TMJ) Dysfunction",
    "Severe Dental Caries",
    "Root Canal Therapy (Endodontics)",
    "Malocclusion and Orthodontic Treatment",
    "Dental Implants and Bone Grafting",
    "Oral Squamous Cell Carcinoma",
    "Gingival Recession",
    "Bruxism and Attrition"
  ]
};

let sqlOutput = `-- Project Echo Database Append Script
-- Autogenerated 150 Professionally Curated Prompts for Dentistry

-- 1. Insert Deck (Dentistry)
INSERT INTO public.decks (id, name, description, icon, theme, accent_color) 
VALUES ('dentistry', 'Dentistry', 'Practice explaining dental procedures, oral health, and treatment plans.', 'Stethoscope', 'Clean, precise, clinical and reassuring.', '#0284c7')
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name, 
  description = EXCLUDED.description, 
  icon = EXCLUDED.icon, 
  theme = EXCLUDED.theme, 
  accent_color = EXCLUDED.accent_color;

-- 2. Update Medicine Deck to remove Dentistry from its name
UPDATE public.decks SET name = 'Medicine', description = 'Practice explaining medical concepts clearly to patients, students, and colleagues.' WHERE id = 'medicine';

-- 3. Insert Prompts
INSERT INTO public.prompts (id, deck_id, prompt, difficulty, active) VALUES
`;

const promptInserts = [];

for (const frame of matrix.frames) {
  for (const subject of matrix.subjects) {
    const promptText = frame.replace('[X]', subject).replace(/'/g, "''");
    const id = crypto.randomUUID();
    const diffs = ['gentle', 'reflective', 'deep'];
    const difficulty = diffs[Math.floor(Math.random() * diffs.length)];
    
    promptInserts.push(`('${id}', '${deckId}', '${promptText}', '${difficulty}', true)`);
  }
}

sqlOutput += promptInserts.join(',\n') + '\nON CONFLICT DO NOTHING;\n';

fs.writeFileSync('supabase/append_dentistry.sql', sqlOutput);
console.log('Successfully generated supabase/append_dentistry.sql with ' + promptInserts.length + ' prompts.');
